# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogSalir.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialogSalir(object):
    def setupUi(self, dialogSalir):
        dialogSalir.setObjectName("dialogSalir")
        dialogSalir.setWindowModality(QtCore.Qt.ApplicationModal)
        dialogSalir.setEnabled(True)
        dialogSalir.resize(350, 100)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dialogSalir.sizePolicy().hasHeightForWidth())
        dialogSalir.setSizePolicy(sizePolicy)
        dialogSalir.setMinimumSize(QtCore.QSize(350, 100))
        dialogSalir.setMaximumSize(QtCore.QSize(350, 100))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iconoWarning/aviso.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dialogSalir.setWindowIcon(icon)
        dialogSalir.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(dialogSalir)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layoutSalir = QtWidgets.QHBoxLayout()
        self.layoutSalir.setObjectName("layoutSalir")
        self.iconSalir = QtWidgets.QLabel(dialogSalir)
        self.iconSalir.setMinimumSize(QtCore.QSize(48, 48))
        self.iconSalir.setMaximumSize(QtCore.QSize(48, 48))
        self.iconSalir.setText("")
        self.iconSalir.setPixmap(QtGui.QPixmap(":/iconoWarning/aviso.png"))
        self.iconSalir.setScaledContents(False)
        self.iconSalir.setObjectName("iconSalir")
        self.layoutSalir.addWidget(self.iconSalir)
        self.lblSalir = QtWidgets.QLabel(dialogSalir)
        self.lblSalir.setMinimumSize(QtCore.QSize(270, 50))
        self.lblSalir.setMaximumSize(QtCore.QSize(270, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblSalir.setFont(font)
        self.lblSalir.setObjectName("lblSalir")
        self.layoutSalir.addWidget(self.lblSalir)
        self.verticalLayout.addLayout(self.layoutSalir)
        self.botones = QtWidgets.QDialogButtonBox(dialogSalir)
        self.botones.setOrientation(QtCore.Qt.Horizontal)
        self.botones.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.botones.setObjectName("botones")
        self.verticalLayout.addWidget(self.botones)

        self.retranslateUi(dialogSalir)
        self.botones.accepted.connect(dialogSalir.accept)
        self.botones.rejected.connect(dialogSalir.reject)
        QtCore.QMetaObject.connectSlotsByName(dialogSalir)

    def retranslateUi(self, dialogSalir):
        _translate = QtCore.QCoreApplication.translate
        dialogSalir.setWindowTitle(_translate("dialogSalir", "Salir"))
        self.lblSalir.setText(_translate("dialogSalir", "¿Esta seguro de que desea salir del programa?"))
import rc_iconosDialog_rc
