# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PYQT5_dialogCalendario.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialogCalendario(object):
    def setupUi(self, dialogCalendario):
        dialogCalendario.setObjectName("dialogCalendario")
        dialogCalendario.setWindowModality(QtCore.Qt.ApplicationModal)
        dialogCalendario.resize(380, 240)
        dialogCalendario.setMinimumSize(QtCore.QSize(380, 240))
        dialogCalendario.setMaximumSize(QtCore.QSize(380, 240))
        dialogCalendario.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(dialogCalendario)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widgetCalendario = QtWidgets.QCalendarWidget(dialogCalendario)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetCalendario.sizePolicy().hasHeightForWidth())
        self.widgetCalendario.setSizePolicy(sizePolicy)
        self.widgetCalendario.setMinimumSize(QtCore.QSize(380, 240))
        self.widgetCalendario.setMaximumSize(QtCore.QSize(380, 240))
        self.widgetCalendario.setObjectName("widgetCalendario")
        self.gridLayout.addWidget(self.widgetCalendario, 0, 0, 1, 1)

        self.retranslateUi(dialogCalendario)
        QtCore.QMetaObject.connectSlotsByName(dialogCalendario)

    def retranslateUi(self, dialogCalendario):
        _translate = QtCore.QCoreApplication.translate
        dialogCalendario.setWindowTitle(_translate("dialogCalendario", "Dialog"))
